zsh_add_file "$ZSH_DIR/functions/work/bundles.sh"
zsh_add_file "$ZSH_DIR/functions/work/db.sh"
zsh_add_file "$ZSH_DIR/functions/work/git.sh"
zsh_add_file "$ZSH_DIR/functions/work/java.sh"
zsh_add_file "$ZSH_DIR/functions/work/others.sh"
zsh_add_file "$ZSH_DIR/functions/work/properties.sh"
zsh_add_file "$ZSH_DIR/functions/work/solr.sh"