zsh_add_file "$ZSH_DIR/custom/zsh-vim-mode.sh"
zsh_add_file "$ZSH_DIR/custom/zsh-prompt.sh"
zsh_add_file "$ZSH_DIR/aliases/work.sh"
zsh_add_file "$ZSH_DIR/aliases/zsh.sh"
zsh_add_file "$ZSH_DIR/functions/work/bundles.sh"
zsh_add_file "$ZSH_DIR/functions/work/db.sh"
zsh_add_file "$ZSH_DIR/functions/work/git.sh"
zsh_add_file "$ZSH_DIR/functions/work/gw.sh"
zsh_add_file "$ZSH_DIR/functions/work/java.sh"
zsh_add_file "$ZSH_DIR/functions/work/ci.sh"
zsh_add_file "$ZSH_DIR/functions/work/others.sh"
zsh_add_file "$ZSH_DIR/functions/work/properties.sh"
zsh_add_file "$ZSH_DIR/functions/work/solr.sh"

unset NPM_CONFIG_PREFIX # Adding this so I can use NVM